use_frameworks!

target 'RTFCPTextFieldCustomizablePlaceholder_Example' do
  pod 'RTFCPTextFieldCustomizablePlaceholder', :path => '../'

  target 'RTFCPTextFieldCustomizablePlaceholder_Tests' do
    inherit! :search_paths

    
  end
end
