source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


def import_pods
	pod "RTFCPTextFieldCustomizablePlaceholder", :path => "../"
end


target 'RTFCPTextFieldCustomizablePlaceholder_Example', :exclusive => true do
  import_pods
end

target 'RTFCPTextFieldCustomizablePlaceholder_Tests', :exclusive => true do
  import_pods

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
